# Site settings
title: Abhi G
email: gaikwad.abhijit@gmail.com
description: "Abhijit Gaikwad, Software Engineer, Actuate"
baseurl: ""
url: "http://gabhi.com"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge