# Site settings
title: Abhi G
email: gaikwad.abhijit@gmail.com
description: "Abhijit Gaikwad, Software Engineer, Actuate"
baseurl: ""
url: "http://gabhi.com"

username:
    twitter:   gaikwad_abhijit
    github:  gabhi
# Build settings
markdown: kramdown
permalink: :title

highlighter: rouge